### ISSUE TITLE
Why are .keys for Namespaces not the same type as for dictionaries?

### ISSUE THREAD

**Issue by brando90** [pcattori/namespaces#31]
I noticed that .keys does not have the same type. For example:

```
>>> d = {'a':1, 'b':2}
>>> type( d.keys() )
<class 'dict_keys'>

>>> dns = ns.Namespace(a=1,b=2)
>>> type(dns.keys())
<class 'collections.abc.KeysView'>
```

Is that suppose to happen?

**Comment by brando90** [comment]
I thought the abstraction was to (nearly) think of NS as dictionaries but with dot notation, so maybe it should act the same as dictionaries when treated as a dict?

**Comment by brando90** [comment]
btw I know `type( dict(dns).keys() )` this works, that wasn't the point though.

**Comment by pcattori** [comment]
`dict_keys` is just a built-in implementation of a [Keys View](https://www.python.org/dev/peps/pep-3106/) for `dict`s. `collections.abc.KeysView` is just the implementation that the [Abstract Base Classes (ABC)](https://docs.python.org/2/library/collections.html#collections-abstract-base-classes) `collections.Mapping` and `collections.MutableMapping` have for a Keys View.

Unless you depend on the type of that object, they should be equivalent as they implement the same interface.

**Comment by brando90** [comment]
I see. As a user, I don't know (or need to know) about that equivalence. So it looked really weird to a user. Just wanted to point it out.
