### ISSUE TITLE
consider using types.SimpleNameSpace

### ISSUE THREAD

**Issue by AlJohri** [pcattori/namespaces#35]
consider using the [types.SimpleNamespace](https://docs.python.org/3.5/library/types.html#additional-utility-classes-and-functions) or if not, document how its different

also as a side note check, out the `!r` which gets the repr of the argument:
```
"Bring out the holy {name!r}"    # Calls repr() on the argument first
```
https://docs.python.org/3/library/string.html#formatexamples

**Comment by pcattori** [comment]
`SimpleNamespace` is not a mapping type. `Namespace` and `FrozenNamespace` can be used as drop-in replacements for `dict`s, but `SimpleNamespace`s cannot.

As for `!r`, I felt that it made the code less legible. That said, I think I like it better now 😄 so maybe I will use it
